<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\app_icon.ico</ApplicationIcon>
    <ApplicationManifest>App.manifest</ApplicationManifest>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>CrosshairZoom</AssemblyName>
    <RootNamespace>CrosshairZoom</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app_icon.ico" />
  </ItemGroup>
</Project>
